# Gruvbox Dark Theme
# https://github.com/morhetz/gruvbox

[colors]
#
#card_bg = #373030 
#card_selected = #b35645
#text_color = #ffffff
#subtext_color = #DEDEDE
#border_color = #1A1414 

background = #1A1414 
card_bg = #2d2121
card_selected = #FF836B
text_color = #FFFFFF
subtext_color = #CFCFCF
border_color = #2d2121

   # background-alt:     #2d2121;z
    #foreground:     #FFFFFF;
    #selected:       #FF836B;
    #active:         #a6e3a1;
    #urgent:         #f38ba8;